# .travis.yml
# This file should be at the root of your project   

language: ruby
cache: bundler
before_install:
  - gem update --system 3.1.1
  - gem install bundler
script:
  - bundle exec jekyll build
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.5.3