---
label: Base
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
