---
label: Base
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- name: link
  type: text
  config:
    required: false
  label: link
pages:
- _posts/puebra-de-enlace-del-titulo.md
