---
label: Base
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- name: permalink
  type: text
  config:
    required: false
  label: permalink
- name: excerpt
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: excerpt
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: header
  type: field_group
  config: {}
  fields:
  - name: overlay_image
    type: text
    config:
      required: false
    label: overlay_image
  - name: image_description
    type: text
    config:
      required: false
    label: image_description
  - name: caption
    type: text
    config:
      required: false
    label: caption
  - name: overlay_filter
    type: text
    config:
      required: false
    label: overlay_filter
  label: header
- name: image
  type: file
  config:
    maxSize: 250
  label: image
pages:
- _posts/2019-04-18-welcome-to-jekyll.md
