---
label: Base
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- name: permalink
  type: text
  config:
    required: false
  label: permalink
pages:
- _posts/wikipedia/2019-08-07-prueba-uno.md
- _posts/2019-04-18-welcome-to-jekyll.md
